[tool.poetry]
name = "termtyper"
version = "2.0.0"
description = "A TUI based typing application"
authors = ["kraanzu <kraanzu@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
textual = "^0.47.1"
appdirs = "^1.4.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.17.0"
black = "^22.1.0"
ruff = "^0.1.5"
textual-dev = "^1.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
termtyper = 'termtyper.__init__:main'

[tool.ruff]
exclude = ["venv"]
